complete --command zig --exclusive --long help --description "Print help"
complete --command zig --exclusive --long version --description "Print version"
complete --command zig --exclusive --long zen --description "Print zen"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments build --description "Build project from build.zig"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments init-exe --description "Initialize a `zig build` application in the cwd"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments init-lib --description "Initialize a `zig build` library in the cwd"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments ast-check --description "Look for simple compile errors in any set of files"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments build-exe --description "Create executable from source or object files"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments build-lib --description "Create library from source or object files"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments build-obj --description "Create object from source or object files"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments fmt --description "Reformat Zig source into canonical form"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments run --description "Create executable and run immediately"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments test --description "Create and run a test build"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments translate-c --description "Convert C code to Zig code"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments ar --description "Use Zig as a drop-in archiver"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments cc --description "Use Zig as a drop-in C compiler"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments c++ --description "Use Zig as a drop-in C++ compiler"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments dlltool --description "Use Zig as a drop-in dlltool.exe"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments lib --description "Use Zig as a drop-in lib.exe"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments ranlib --description "Use Zig as a drop-in ranlib"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments env --description "Print lib path, std path, cache directory, and version"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments libc --description "Display native libc paths file or validate one"
complete --command zig --exclusive --condition __fish_use_subcommand --arguments targets --description "List available compilation targets"
